name: Upload Docker Dev Container

on:
  push:
    branches:    
      - 'main'
      - 'master'

jobs:
  deploy_ghcr_only:
    if: github.repository!='opsdroid/opsdroid' && vars.ALLOW_DEPLOYMENTS=='true' # only run on forks with the opt-in variable; no need for docker hub there
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: builder
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/opsdroid
        tags: |
          type=raw,value=dev
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        platforms: linux/amd64
        labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    if: github.repository=='opsdroid/opsdroid' # only run on official repo, not on forks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64,arm'
    - name: Set up Docker Buildx
      id: builder
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ secrets.DOCKERHUB_REPO }}
          ghcr.io/${{ github.repository_owner }}/opsdroid
        tags: |
          type=raw,value=dev
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        platforms: linux/amd64,linux/arm64,linux/arm
        labels: ${{ steps.docker_meta.outputs.labels }}
